services:
  backend:
    build:
      context: ./backend
      
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: production
      PIP_PATH: /usr/local/bin/pip
    ports:
      - 5000:5000
    privileged: true
  frontend:
    build:
      context: ./frontend
    environment:
      NODE_ENV: production
    ports:
      - 80:80